#
#           Контакты разработчика:
#               VK: vk.com/dimawinchester
#               Telegram: t.me/teanus
#               Github: github.com/teanus
#
#
#
# ████████╗███████╗ █████╗ ███╗   ██╗██╗   ██╗███████╗
# ╚══██╔══╝██╔════╝██╔══██╗████╗  ██║██║   ██║██╔════╝
#    ██║   █████╗  ███████║██╔██╗ ██║██║   ██║███████╗
#    ██║   ██╔══╝  ██╔══██║██║╚██╗██║██║   ██║╚════██║
#    ██║   ███████╗██║  ██║██║ ╚████║╚██████╔╝███████║
#    ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝ ╚═════╝ ╚══════╝


Telegram:
  token: ""
  on_logger_group: False  # логирование в группе телеграм (True - вкл, False - выкл)
  logger_chat_id: ''  # id группы для логирования бота (если включено)

database:
  name: 'rcon_bot.db'

rcon:
  HOST: "127.0.0.1"
  PASSWORD: "pass"
  PORT: 25576

console:
  give_role: False
